
# Site Config

title: Zenith Digital
email: hello@zenith-digital.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Zenith Digital, steered by a director with extensive experience in film, 
  TV, broadcast, and theatre, excels in Unreal Engine technology. 
  We offer custom solutions that transform stories through advanced real-time rendering and visual effects.
  Our commitment to personalized service, adaptable to each unique project, 
  ensures a focus on innovation, excellence, and captivating storytelling. 
  Zenith Digital stands at the forefront of evolving digital narratives, 
  skillfully handling everything from cutting-edge 
  theatrical productions to groundbreaking television series.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://zenith-digital.co.uk
twitter_username: 
github_username:  zenith-digital


# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
